// <auto-generated />
using System.Collections.Generic;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BusDbContext))]
    [Migration("20260504152240_AddedFavStops_DeletedStopPlaces")]
    partial class AddedFavStops_DeletedStopPlaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.FavStops", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("bigint");

                    b.PrimitiveCollection<List<int>>("StopIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("ChatId");

                    b.ToTable("FavStops");
                });
#pragma warning restore 612, 618
        }
    }
}
